alias rc='rails c'
alias rs='rails s'
alias rg='rails g'
alias rnb='rails new -d postgresql -T'
alias geeknote='python2 ~/.local/bin/geeknote'
# alias tmux='tmux -2'
alias mux='tmuxinator'
# alias tmux='TERM=screen-256-color-bce tmux'
alias tm='tmux new-session -A -D -s 0'
