anchors:
  - &left 'ADEAAGQyZAA='
  - &right 'ZDIAnQAxZAA='
  - &up 'OWQAyioAZAA='
  - &down 'MAAAMDNkZAA='

  - &left_then_up 'VWMAYw5kKdMXKEzOFgBkAA=='
  - &right_then_down 'AA4ALQhRKQFkVWFkYFVkAA=='

  - &top_right_to_bottom_left 'ZBEAVC4tMk4AUmQA'
  - &bottom_left_to_top_right 'AFgA7GQLZAA='

  - &tilde 'ADUA6xAoEfkbJRsWNz05AkM+QvZYN1TlZClkAA=='

  - &letter_e 'Bi4AADwvEOVPGhnNTQgeni0GKFYXEDBMBh83OQA9QBcYU0oIPl1WAExdWutkS2QA'
  - &letter_f 'ECAAADwfE+hTCSGnNwAvUykHNj4kFTwhQktYNT9kZAA='

  - &kpat_shape 'GE4A61AhGN9YEh2dABA7FxIgQxNJRlkOZFNjxGNTZAA='

mouse:
  gestures:
    - type: stroke
      strokes: [ *left ]
      mouse_buttons: [ right ]
      actions:
        - command: niri msg action focus-column-left

    - type: stroke
      strokes: [ *right ]
      mouse_buttons: [ right ]
      actions:
        - command: niri msg action focus-column-right

    - type: stroke
      strokes: [ *up ]
      mouse_buttons: [ right ]
      actions:
        - command: niri msg action focus-window-or-workspace-down

    - type: stroke
      strokes: [ *down ]
      mouse_buttons: [ right ]
      actions:
        - command: niri msg action focus-window-or-workspace-up

    - type: stroke
      strokes: [ *left_then_up ]
      mouse_buttons: [ right ]
      actions:
        - command: niri msg action open-overview

    - type: stroke
      strokes: [ *right_then_down ]
      mouse_buttons: [ right ]
      actions:
        - command: niri msg action close-window

    - type: stroke
      strokes: [ *top_right_to_bottom_left ]
      mouse_buttons: [ right ]
      actions:
        - command: niri msg action switch-preset-column-width

    - type: stroke
      strokes: [ *bottom_left_to_top_right ]
      mouse_buttons: [ right ]
      actions:
        - command: niri msg action maximize-column

    - type: stroke
      strokes: [ *tilde ]
      mouse_buttons: [ right ]
      actions:
        - command: niri msg action toggle-window-floating

    - type: stroke
      strokes: [ *letter_e ]
      mouse_buttons: [ right ]
      actions:
        - command: pcmanfm

    - type: stroke
      strokes: [ *letter_f ]
      mouse_buttons: [ right ]
      actions:
        - command: firefox

    - type: stroke
      strokes: [ *kpat_shape ]
      mouse_buttons: [ right ]
      actions:
        - command: kpat
