require("plugins.diagnostics")
require("lazy").setup({
  { "christoomey/vim-tmux-navigator" },
  { "qpkorr/vim-bufkill" },
  { "vim-scripts/loremipsum" },
  --{"mattn/emmet-vim"},
  --{"iamcco/coc-tailwindcss"},
  --{"elzr/vim-json"},
  --{"wavded/vim-stylus"},
  { "purescript-contrib/purescript-vim" },
  { "nwolverson/purescript-language-server" },
  { "natefaubion/purescript-tidy" },
  { "nvim-lua/plenary.nvim" },
  { "shaunsingh/nord.nvim" },
  { "folke/tokyonight.nvim" },
  { "tpope/vim-obsession" },
  --{"chazy/dirsettings"},
  {
    "mason-org/mason.nvim",
    opts = {},
  },
  { import = "plugins.tree-sitter" },
  { import = "plugins.noice" },
  { import = "plugins.indentmini" },
  { import = "plugins.neotree" },
  { import = "plugins.comment" },
  { import = "plugins.telescope" },
  { import = "plugins.bufferline" },
  { import = "plugins.lualine" },
  { import = "plugins.null-ls" },
  { import = "plugins.tiny-inline-diagnostics" },
  { import = "plugins.nordic" },
  { import = "plugins.gitsigns" },
  { import = "plugins.supermaven" },
  { import = "plugins.nvim-cmp" },
  { import = "plugins.rainbow-delimiters" },
  { import = "plugins.hop" },
  { import = "plugins.mini-surround" },
  { import = "plugins.mini-icons" },
  { import = "plugins.markdown" },
  -- need to revisit this later
  -- { import = "plugins.fugitive" },
})
