require("lazy").setup({
  { "christoomey/vim-tmux-navigator" },
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  {"qpkorr/vim-bufkill"},
  {"tpope/vim-surround"},
  {"tpope/vim-repeat"},
  {"phaazon/hop.nvim"},
  {"terryma/vim-multiple-cursors"},
  {"vim-scripts/loremipsum"},
  {"mattn/emmet-vim"},
  {"iamcco/coc-tailwindcss"},
  {"hiphish/rainbow-delimiters.nvim"},
  {"elzr/vim-json"},
  {"HerringtonDarkholme/yats.vim"},
  {"heavenshell/vim-jsdoc"},
  {"jparise/vim-graphql"},
  {"digitaltoad/vim-pug"},
  {"wavded/vim-stylus"},
  {"purescript-contrib/purescript-vim"},
  {"nwolverson/purescript-language-server"},
  {"natefaubion/purescript-tidy"},
  {"tpope/vim-fugitive"},
  {"nvim-lua/plenary.nvim"},
  {"lewis6991/gitsigns.nvim"},
  {"APZelos/blamer.nvim"},
  {"preservim/nerdcommenter"},
  {"andersevenrud/nordic.nvim"},
  {"shaunsingh/nord.nvim"},
  {"folke/tokyonight.nvim"},
  {"ujihisa/nclipper.vim"},
  {"tpope/vim-obsession"},
  {"iamcco/markdown-preview.nvim", build =  "cd app & yarn install"},
  {"chazy/dirsettings"},
  { import = "plugins.nvim-cmp" },
  { "hrsh7th/cmp-nvim-lsp" },
  { "hrsh7th/cmp-path" },
  { "hrsh7th/cmp-cmdline" },
  { import = "plugins.cmp-tabnine" },
  {
    "mason-org/mason.nvim",
    opts = {}
  },
  { "onsails/lspkind.nvim" },
  { import = "plugins.noice" },
  { import = "plugins.indentmini" },
  { import = "plugins.neotree" },
  { import = "plugins.comment" },
  { import = "plugins.telescope" },
  { import = "plugins.bufferline" },
  { import = "plugins.lualine" },
  { import = "plugins.null-ls" },
})

require("plugins.diagnostics")
