require("plugins.diagnostics")
require("lazy").setup({
  { "christoomey/vim-tmux-navigator" },
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  { "qpkorr/vim-bufkill" },
  { "tpope/vim-surround" },
  { "tpope/vim-repeat" },
  { "phaazon/hop.nvim" },
  { "terryma/vim-multiple-cursors" },
  { "vim-scripts/loremipsum" },
  --{"mattn/emmet-vim"},
  --{"iamcco/coc-tailwindcss"},
  --{"elzr/vim-json"},
  --{"HerringtonDarkholme/yats.vim"},
  --{"heavenshell/vim-jsdoc"},
  --{"jparise/vim-graphql"},
  --{"digitaltoad/vim-pug"},
  --{"wavded/vim-stylus"},
  { "purescript-contrib/purescript-vim" },
  { "nwolverson/purescript-language-server" },
  { "natefaubion/purescript-tidy" },
  --{"tpope/vim-fugitive"},
  { "nvim-lua/plenary.nvim" },
  { "shaunsingh/nord.nvim" },
  --{"folke/tokyonight.nvim"},
  --{"ujihisa/nclipper.vim"},
  { "tpope/vim-obsession" },
  --{"iamcco/markdown-preview.nvim", build =  "cd app & yarn install"},
  --{"chazy/dirsettings"},
  {
    "mason-org/mason.nvim",
    opts = {},
  },
  { import = "plugins.noice" },
  { import = "plugins.indentmini" },
  { import = "plugins.neotree" },
  { import = "plugins.comment" },
  { import = "plugins.telescope" },
  { import = "plugins.bufferline" },
  { import = "plugins.lualine" },
  { import = "plugins.null-ls" },
  { import = "plugins.tiny-inline-diagnostics" },
  { import = "plugins.nordic" },
  { import = "plugins.gitsigns" },
  { import = "plugins.cmp-tabnine" },
  { import = "plugins.nvim-cmp" },
  -- that's the culprit
  -- { import = "plugins.rainbow-delimiters" },
})
